server.port=8080
output.base-dir=./output
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
logging.config=classpath:logback.xml
spring.config.import=optional:classpath:config.yml
